### ISSUE TITLE
Bug: Invalid Downscaling Modal shows up even when that section is disabled.

### ISSUE THREAD

**Issue by drew-disher** [vektor9999/NolvusDashboard#10]
Minor thing, but when DLAA is selected, the selected options for down scaling still take effect even when that section is disabled/grayed out. (Get the error on 'Continue' to next step)

![image](https://github.com/vektor9999/NolvusDashboard/assets/116017606/2ca6c08b-453d-49f5-a246-7c3053b7b35c)

**Comment by vektor9999** [comment]
Fixed in 3.5.12
