### ISSUE TITLE
Failed to patch game file : binkw64.dll

### ISSUE THREAD

**Issue by Vanlis551551** [vektor9999/NolvusDashboard#11]
I have such a problem, please help me
<img width="582" alt="Screenshot_2" src="https://github.com/vektor9999/NolvusDashboard/assets/160658786/89fde71d-ba13-4518-a39d-5fc42d04c669">

**Comment by Vanlis551551** [comment]
[Log.txt](https://github.com/vektor9999/NolvusDashboard/files/14350759/Log.txt)

**Comment by maxilam3** [comment]
Same problem for me.

**Comment by Vanlis551551** [comment]
Bro, I fixed it. Just download the latest version from git hub
