### ISSUE TITLE
[SUGGESTION] Enable Windows Long Filenames

### ISSUE THREAD

**Issue by yoiang** [vektor9999/NolvusDashboard#2]
Hey y'all! 
Currently in the installation process, super stoked to play NOLVUS! Thanks so much for all this work!
There are already a bunch of hoops and setup that has to go into ensuring a smooth installation process. To allow for folks to control where the installer stores its business, help people keep their computer organized and remove unnecessary constraints on the application perhaps requiring people go through the steps to [enable long filenames in Windows](https://answers.microsoft.com/en-us/windows/forum/all/how-to-extend-file-path-characters-maximum-limit/691ea463-2e15-452b-8426-8d372003504f) could be wrapped into the process (I've already had to do this for other applications anyways personally!).

Cheers!

**Comment by Ishikudeska** [comment]
hey man what's your discord name? I've got a question or two to ask!

**Comment by vektor9999** [comment]
Added in 3.5.17
