### ISSUE TITLE
Crash while downloading High Poly Head

### ISSUE THREAD

**Issue by Alceris** [vektor9999/NolvusDashboard#4]
Without a premium Nexus account, unsure if that matters, when High Poly Head is supposed to start automatically downloading after starting to download Modpocalypse NPCs - Resources, the installer consistently crashes with the following error.

---------------------------
NolvusDashBoard.exe - Application Error
---------------------------
The exception unknown software exception (0xe0434352) occurred in the application at location 0x00007FF9BF6E4F69.

---------------------------
OK   Cancel   
---------------------------

Manually downloading High Poly Head and placing it in the proper ARCHIVES folder is a functioning workaround for this crash.

**Comment by Alceris** [comment]
Same thing happens with 'BDOR Nova Pack.'

**Comment by FluidExtractor** [comment]
Can confirm. This makes you unable to let the installer run unattended. You constantly have to babysit it in case in randomly crashes.
