### ISSUE TITLE
3 issues: LOD box greyed out, Nvidia card not detected on laptop, dashbaord menu scaling (DPI) preventing "Back" button to show

### ISSUE THREAD

**Issue by Sabbelwookie** [vektor9999/NolvusDashboard#5]
1. Having the issue that I use the REDUX version and the drop down menu for LODs is greyed out with ULTRA as a preselection chosen. This is probably way too high for my laptop yielding me no more than 10-20 FPS - laptop with i10875, GF 2070 Super, 32 GB, Samsung 970 Evo NVME SSD.

2. Another issue (I will open another issue for this, ignore or close as you prefer, vektor) is that the nolvus dashboard only recognizes the intel onboard chip UHD 770(?) and not the 2070 Super. Therefore I can't select DLSS or any nvidia specific feature for tesselation or antialising (the box is greyed out again). I have registered the dashboard application in the nvidia control panel for the 2070 Super, the application just doesn't recognize the nvidia card.

3. Finally (Will open a third issue) I am having issues with the DPI, the nolvus dashboard app is running with. It shows 150%, which is my OS-DPI as well. My laptop has a 1440p screen. The problem is, once sahboard has finished the install, I would like to make some changes with your dashboard app. I can open the menu, but the "back" button after having made the changes is not displayed in the app. When I change my screen resolution to 1080, it is barely visible, but cut off in Y. No scroll bar appears either. The menu options on the right side of the nolvus dashboard are way too spread in Y, it seems, so the back button disappears and I basically can't cofirm any changes.

Besides, thanks alot for nolvus! Great package!! Will definately gift some coin once I have it running.

**Comment by vektor9999** [comment]
For Point 1, redux has its own defined lod and they can't be changed (lods selection is only for Ultra variant)
For Point 2, read this ==> https://www.nolvus.net/appendix/installer/tech
For Point 3, gonna check

**Comment by Sabbelwookie** [comment]
Thanks for your reply.

@1: Just as a suggestion then, you might want to rename the redux LOD from ULTRA to something a bit more intuitive like "Redux LOD" then to prevent any muddle.
@2: My appologizes; should have seen this myself.
@3: Thanks!

**Comment by vektor9999** [comment]
@Sabbelwookie  Point 3 should be fixed, let me know

**Comment by Sabbelwookie** [comment]
Point 3 is fixed, can confirm. Very cool, thank you so much! Now changing stuff later on is possible for me.
