### ISSUE TITLE
License key

### ISSUE THREAD

**Issue by andreluizgaspar** [vektor9999/NolvusDashboard#7]
The Syncfusion license key is hard-coded in the project.
[Locations where it can be found.](https://github.com/search?q=repo%3Avektor9999%2FNolvusDashboard%20MzM2MTU4QDMxMzgyZTMzMmUzMFBiTkxiV0dEMEhlWnowK3IxVUFsYkdGM2VnR0d6RDVBdGNYOEVFK2VqNVk9&type=code)
This is concerning for security reasons, anyone reading the code could steal the key.

**Comment by Ishikudeska** [comment]
In agreement here. License key should either be a non-issue or completely removed!

**Comment by vektor9999** [comment]
This is a free key so it does not matter but i will remove it
